### ISSUE TITLE
rename the default branch to main

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nwfsc-assess/nwfscDiag#10]
The suggested name for the default branch is main rather than master. @chantelwetzel-noaa should we change this or keep it as is?
Users will need to run
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
locally to complete the switch.

**Comment by chantelwetzel-noaa** [comment]
I definitely would like to make this change, however, I was unsure how to do this since I did not use git through the terminal. If you would like to do the change, I can then run the suggested commands locally. @kellijohnson-NOAA Thank you.

**Comment by k-doering-NOAA** [comment]
There may need to be a setting modified on github, too? Not sure: https://docs.github.com/en/organizations/managing-organization-settings/managing-the-default-branch-name-for-repositories-in-your-organization
