### ISSUE TITLE
Priors in likelihood profiles (starter file specification)

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nwfsc-assess/nwfscDiag#16]
@iantaylor-NOAA suggested that we create a new figure that has with the prior and without the prior. 🏆 for everyone!

If you fix the value you have a "point prior" because you are fixing it rather than the actual prior.
3 situations (@iantaylor-NOAA I missed this can you edit this comment)

**Comment by iantaylor-NOAA** [comment]
Duplicate of https://github.com/nwfsc-assess/nwfscDiag/issues/6. I'll copy the comment over and close this.

**Comment by kellijohnson-NOAA** [comment]
Thanks @iantaylor-NOAA sorry I didn't search the issues first.
