### ISSUE TITLE
Intent of run_diag_warning.txt?

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nwfsc-assess/nwfscDiag#7]
@chantelwetzel-noaa I am curious what the main goal of run_diag_warning.txt is? Right now, the file is saved in the current working directory rather than in the retro folder. Also, it includes a vector of TRUE and FALSE statements without context. I am wondering if you wanted users to have access to this information or if you wanted to stop it from printing to the screen? We can stop it by just saving file.copy() to an object rather than printing the output with capture.output(). Or should we add information to the file to give context to what it means and potentially save it in the retro folder? I ran into problems when running models for multiple areas on the same computer, this file was overwritten.

https://github.com/nwfsc-assess/nwfscDiag/blob/17b78d38726e654aaff3bfac6efe77647aa27ead/R/retro_wrapper.R#L23-L25

**Comment by chantelwetzel-noaa** [comment]
During development I had issues preventing the TRUE or FALSE from file.copy being printed to the screen.  This approach was my work around to dump it somewhere other than the screen. Your suggestion of saving the file.copy() to an object sounds reasonable to me.  Also, if you look at line 26, just below this section, you can see a great typo.  I can go ahead and fix both of these items.

**Comment by kellijohnson-NOAA** [comment]
I am in the file right now making some other changes, so I can change it to
```
ignore <- file.copy()
```
which is what I typically do.
I will also fix the typo.

**Comment by iantaylor-NOAA** [comment]
@chantelwetzel-noaa, are you sure that's a typo and not a cutting edge new model diagnostic?

**Comment by chantelwetzel-noaa** [comment]
@kellijohnson-NOAA Thank you.

On my local machine I have also made some changes to the profile setup that would allow users to have explicit control as to whether include the prior likelihood  when setting up the profile settings.  I plan pushing those changes by the end of the week.  I had been putting off this until the lingcod panel concluded.  Now everything is fair game!

**Comment by kellijohnson-NOAA** [comment]
Awesome, I need to rerun all of our profiles still; but, the results need to be done by Friday. Should I wait for your code or just use `model_settings$prior_check`?

**Comment by chantelwetzel-noaa** [comment]
Which would you prefer since it you that would be impacted?  I need to make one more additional change to allow a user to run both a profile with and without the prior in the same call which I had struggled to implement last week but I think I have figured out a solution.  The other changes have been tested so in theory this could be quick.

**Comment by kellijohnson-NOAA** [comment]
Would tomorrow be a reasonable time frame for you to push the changes? Then I can test them out for you.

**Comment by chantelwetzel-noaa** [comment]
That works for me.  I will let you know when all changes are done and pushed.

**Comment by kellijohnson-NOAA** [comment]
Profiles appear to look good. Thank you @chantelwetzel-noaa for modifying the function.
